[rtsp]
mounts = ["cam"]
codec = "h265"
bitrate = 1200000
width = 480
height = 272

[zenoh]
mode = "client"
server_ip = "172.20.10.5"
server_port = 7447
connect = []
listen = []
key_prefix = "rk_studio"

[entity]
entity_id = "helmet_001"
display_name = "张三的头盔"
owner = "operator_01"
device_type = "helmet"
provides_channels = "video_out,mediapipe"
video_stream_url = "rtsp://172.20.10.3:8554/cam"

[yolo]
model = "../models/yolo11n_rk3588_int8.rknn"
fps = 5
confidence_threshold = 0.25
nms_threshold = 0.45
max_detections = 50

[face_expression]
detector_model = "../models/face_detection_yunet_2023mar_rk3588_int8.rknn"
expression_model = "../models/face_expression_mobilefacenet_2022july_rk3588_int8.rknn"
expression_labels = ["angry", "disgust", "fearful", "happy", "neutral", "sad", "surprised"]
fps = 10
confidence_threshold = 0.2
nms_threshold = 0.4
expression_threshold = 0.2
max_faces = 1

[audio_event]
model = "../models/yamnet.onnx"
class_map = "../models/yamnet_class_map.csv"
fps = 2
window_ms = 960
hop_ms = 480
top_k = 5
score_threshold = 0.20
publish_threshold = 0.30

[audio.mic0]
device = "hw:rockchipes8388,0"

[camera.cam0]
record_device = "/dev/video44"
orientation = "normal"
preview_width = 640
preview_height = 360
fps = 20

[camera.cam1]
record_device = "/dev/video53"
orientation = "rotate-180"
preview_width = 640
preview_height = 360
fps = 20

[camera.cam2]
record_device = "/dev/video62"
orientation = "rotate-180"
preview_width = 640
preview_height = 360
fps = 20

[camera.cam3]
record_device = "/dev/video71"
orientation = "normal"
preview_width = 640
preview_height = 360
fps = 20
